name: Frontend Deploy to ECR

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ID }}
          aws-secret-access-key: ${{ secrets.AWS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and Push Images
        run: |
          # 프론트엔드 ECR 리포지토리 이름(community-fe) 확인
          docker build -t ${{ steps.login-ecr.outputs.registry }}/community-fe:latest .
          docker push ${{ steps.login-ecr.outputs.registry }}/community-fe:latest